### ISSUE TITLE
RuntimeError: Task got Future attached to a different loop on Raspberry Pi

### ISSUE THREAD

**Issue by tkem** [tkem/carreralib#18]
On a Raspberry Pi 3 Model B+ with latest Pi OS (Debian "bullseye"):
```
>>> from carreralib import ControlUnit
>>> cu = ControlUnit('D3:14:BB:32:C5:75')
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.9/site-packages/carreralib/ble.py", line 28, in run
    asyncio.run(self.main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.9/site-packages/carreralib/ble.py", line 78, in main
    data = await self.__output.get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-1' coro=<BleakThread.main() running at /home/pi/.local/lib/python3.9/site-packages/carreralib/ble.py:78> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop
```

**Comment by tkem** [comment]
It's apparently required to create `asyncio.Queue` with the proper active event loop (note the loop cannot be passed as an argument). Why this breaks only on Raspberry Pi and not on e.g. Ubuntu or Windows beats me.
